"use client";

import React, { useState } from "react";
import { useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";

// One-time kiosk pairing. Technician types a 6-digit code generated by an
// admin (any store) or by a store owner logged into /store/settings. The
// server returns a long-lived deviceToken that this kiosk uses on every
// subsequent mutation — see convex/kioskAuth.ts.
export default function KioskSetupPage() {
  const [digits, setDigits] = useState<string[]>(["", "", "", "", "", ""]);
  const [deviceLabel, setDeviceLabel] = useState("");
  const [step, setStep] = useState<"code" | "done">("code");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<{ storeName: string; deviceId: string } | null>(null);

  const consumeCode = useMutation(api.kioskPairing.consumePairingCode);
  const inputsRef = React.useRef<Array<HTMLInputElement | null>>([]);

  const handleDigit = (i: number, v: string) => {
    const d = v.replace(/\D/g, "").slice(-1);
    const next = [...digits];
    next[i] = d;
    setDigits(next);
    setError("");
    if (d && i < 5) inputsRef.current[i + 1]?.focus();
  };

  const handleKeyDown = (i: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !digits[i] && i > 0) {
      inputsRef.current[i - 1]?.focus();
    }
  };

  const handleSubmit = async () => {
    const code = digits.join("");
    if (code.length !== 6) {
      setError("Enter the 6-digit code");
      return;
    }
    setLoading(true);
    setError("");
    try {
      const res = await consumeCode({
        code,
        deviceLabel: deviceLabel.trim() || undefined,
      });
      const config = {
        storeId: res.storeId,
        storeName: res.storeName,
        deviceId: res.deviceId,
        deviceToken: res.deviceToken,
        deviceLabel: res.deviceLabel,
        pairedAt: Date.now(),
      };
      localStorage.setItem("wearify_kiosk_store", JSON.stringify(config));
      window.dispatchEvent(new Event("kiosk-configured"));
      setResult({ storeName: res.storeName, deviceId: res.deviceId });
      setStep("done");
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : "Pairing failed";
      setError(msg.replace(/^Error: /, ""));
      setDigits(["", "", "", "", "", ""]);
      inputsRef.current[0]?.focus();
    } finally {
      setLoading(false);
    }
  };

  if (step === "done" && result) {
    return (
      <div style={{
        flex: 1,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 32,
      }}>
        <div style={{ textAlign: "center", width: "100%", maxWidth: 440 }}>
          <div style={{
            width: 72, height: 72, borderRadius: "50%",
            background: "var(--k-green-bg)",
            border: "2px solid rgba(45,133,68,.3)",
            display: "flex", alignItems: "center", justifyContent: "center",
            margin: "0 auto 20px", fontSize: 32, color: "var(--k-green)",
          }}>
            ✓
          </div>
          <h1 style={{ fontSize: 26, fontWeight: 700, color: "var(--k-text)", margin: "0 0 8px" }}>
            Kiosk Paired
          </h1>
          <p style={{ fontSize: 15, color: "var(--k-text-muted)", margin: "0 0 6px" }}>
            Store: <strong style={{ color: "var(--k-text)" }}>{result.storeName}</strong>
          </p>
          <p style={{ fontSize: 12, color: "var(--k-text-light)", margin: "0 0 28px", fontFamily: "'Roboto Mono', monospace" }}>
            Device ID: {result.deviceId}
          </p>
          <button
            onClick={() => (window.location.href = "/kiosk")}
            style={{
              padding: "14px 40px",
              borderRadius: 14,
              background: "var(--k-maroon)",
              color: "#fff",
              fontSize: 16,
              fontWeight: 600,
              border: "none",
              cursor: "pointer",
            }}
          >
            Launch Kiosk →
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={{
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
    }}>
      <div style={{ width: "100%", maxWidth: 440 }}>
        {/* Header */}
        <div style={{ textAlign: "center", marginBottom: 32 }}>
          <div style={{
            width: 56, height: 56, borderRadius: "50%",
            background: "rgba(107,26,26,.1)",
            border: "1.5px solid rgba(107,26,26,.25)",
            display: "flex", alignItems: "center", justifyContent: "center",
            margin: "0 auto 16px",
          }}>
            <span style={{
              fontSize: 20, fontWeight: 800, color: "var(--k-gold)",
              fontFamily: "'Cormorant Garamond', serif", fontStyle: "italic",
            }}>W</span>
          </div>
          <h1 style={{
            fontSize: 24, fontWeight: 700, color: "var(--k-text)",
            margin: "0 0 6px", letterSpacing: -0.5,
          }}>
            Pair this kiosk
          </h1>
          <p style={{ fontSize: 14, color: "var(--k-text-muted)", margin: 0 }}>
            Ask the store owner or admin for a 6-digit pairing code
          </p>
        </div>

        {/* 6-digit code boxes */}
        <label style={{
          display: "block", fontSize: 12, fontWeight: 600,
          color: "var(--k-text-mid)", textTransform: "uppercase",
          letterSpacing: 1, marginBottom: 10,
        }}>
          Pairing Code
        </label>
        <div style={{ display: "flex", gap: 8, justifyContent: "space-between", marginBottom: 16 }}>
          {digits.map((d, i) => (
            <input
              key={i}
              ref={(el) => { inputsRef.current[i] = el; }}
              type="text"
              inputMode="numeric"
              maxLength={1}
              value={d}
              onChange={(e) => handleDigit(i, e.target.value)}
              onKeyDown={(e) => handleKeyDown(i, e)}
              autoFocus={i === 0}
              style={{
                flex: 1,
                minWidth: 0,
                padding: "16px 0",
                borderRadius: 10,
                background: "var(--k-card)",
                border: "1.5px solid var(--k-border)",
                color: "var(--k-text)",
                fontSize: 26,
                fontFamily: "'Roboto Mono', monospace",
                textAlign: "center",
                outline: "none",
              }}
              onFocus={(e) => { e.currentTarget.style.borderColor = "var(--k-maroon)"; }}
              onBlur={(e) => { e.currentTarget.style.borderColor = "var(--k-border)"; }}
            />
          ))}
        </div>

        <label style={{
          display: "block", fontSize: 12, fontWeight: 600,
          color: "var(--k-text-mid)", textTransform: "uppercase",
          letterSpacing: 1, marginBottom: 8,
        }}>
          Device label (optional)
        </label>
        <input
          type="text"
          value={deviceLabel}
          onChange={(e) => setDeviceLabel(e.target.value)}
          placeholder="e.g. Front mirror, Trial room 2"
          style={{
            width: "100%",
            padding: "12px 16px",
            borderRadius: 10,
            background: "var(--k-card)",
            border: "1.5px solid var(--k-border)",
            color: "var(--k-text)",
            fontSize: 15,
            outline: "none",
            boxSizing: "border-box",
            marginBottom: 16,
          }}
        />

        {error && (
          <p style={{
            fontSize: 13, color: "var(--k-red)",
            margin: "0 0 12px", textAlign: "center",
          }}>
            {error}
          </p>
        )}

        <button
          onClick={handleSubmit}
          disabled={loading || digits.join("").length !== 6}
          style={{
            width: "100%",
            padding: "14px 0",
            borderRadius: 12,
            background: loading || digits.join("").length !== 6 ? "var(--k-border)" : "var(--k-maroon)",
            color: "#fff",
            fontSize: 16,
            fontWeight: 600,
            border: "none",
            cursor: loading || digits.join("").length !== 6 ? "not-allowed" : "pointer",
          }}
        >
          {loading ? "Pairing..." : "Pair kiosk"}
        </button>

        <p style={{
          fontSize: 11, color: "var(--k-text-light)",
          margin: "18px 0 0", textAlign: "center", lineHeight: 1.5,
        }}>
          Codes expire 2 minutes after they&rsquo;re generated.
          <br />
          Ask the store owner to generate a fresh one if yours has timed out.
        </p>
      </div>
    </div>
  );
}
